[Translate] Web 3.0 入门指南
openbuildxyz/OpenContent pull request #26
Opened 2024-04-02 06:25 UTC by coco723

任务领取，翻译 https://github.com/openbuildxyz/OpenContent/issues/1

2024-04-05 14:37 UTC, xilibi2003 requested changes

2024-04-05 14:37 UTC, xilibi2003 commented on _posts/Article/Translation/The-ultimate-guide-to-web-3/the-ultimate-guide-to-web-3.md
> +现在，您已经对网络的演变及其旧有阶段有了很好的了解，让我们来了解一下 Web 3.0 到底是什么。
翻译时， 同一个词，最好是一直的翻译，建议使用  你 而不是 您

2024-04-07 07:50 UTC, coco723 commented on _posts/Article/Translation/The-ultimate-guide-to-web-3/the-ultimate-guide-to-web-3.md
> +现在，您已经对网络的演变及其旧有阶段有了很好的了解，让我们来了解一下 Web 3.0 到底是什么。
done

2024-04-23 12:58 UTC, xilibi2003 approved these changes

2024-04-23 12:58 UTC, merged