How does the NEW Ethereum work 翻译
openbuildxyz/OpenContent pull request #7
Opened 2024-03-08 08:11 UTC by sumisme945

2024-03-13 01:58 UTC, Jiahui-Zeng requested changes

2024-03-13 01:58 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +“女巫抵抗”是共识算法如何确保恶意用户无法创建多个帐户并通过欺诈性投票颠覆网络（称为女巫攻击）。PoW使用计算能力作为女巫抵抗机制。换句话说，你需要硬件来解决工作量证明哈希，因此每个“投票”都由硬件单元支持。同理，PoS使用金钱作为女巫抵抗机制。在这种情况下，每次投票背后其实都是金钱。
“抵抗女巫攻击”是确保恶意用户无法创建多个帐户并通过欺诈性投票来颠覆网络的共识算法（这个过程称为女巫攻击）。PoW使用算力作为抵抗女巫攻击的机制。换句话说，你需要硬件来解决工作量证明哈希，因此每个“投票”都由硬件单元支持。另一方面，PoS使用金钱作为抵抗女巫攻击的机制。在这种情况下，每一票都由金钱（权益）支撑。

2024-03-18 06:02 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +### 以太坊发生了哪些变化？
## 以太坊发生了哪些变化？

2024-03-18 06:03 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +##### 1. 测试网
### 1. 测试网

2024-03-18 06:20 UTC, Jiahui-Zeng requested changes

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +##### 2. 客户端
### 2. 客户端

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +##### 4. 操作码的变化
### 4. 操作码的变化

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +"mixHash"是另一个只与挖矿相关的字段，但该字段现在将包含Beacon链的"RANDAO"值（我们将在下文中解释），没有被设置为0。
"**mixHash**"是另一个只与挖矿相关的字段，但该字段现在将包含Beacon链的"**RANDAO**"值（我们将在下文中解释），没有被设置为0。

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +##### 5. Block Time
### 5. 区块时间

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +##### 6. Finalized Blocks & Safe Head
### 6. 最终确定的区块 & 安全的头块（Safe Head）

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +#### 对以太坊的长期影响
## 对以太坊的长期影响

2024-03-18 06:20 UTC, Jiahui-Zeng commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +### 结论
## 结论

2024-03-21 07:43 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +当以太坊用权益证明(Proof-of-Stake，简称PoS)取代工作量证明(Proof-of-Work，简称PoW)共识时，我们称之为“合并(The Merge)”。从那时起，以太坊就不再需要矿工来执行工作证明并向区块链添加新区块。相反，它使用“验证者”，它们通过质押ETH来获得验证新区块并将新区块添加到区块链的权利。
3ks

2024-03-21 07:59 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +那么，首先什么是PoS呢？这就是我们将在博客文章的其余部分中探讨的内容，"The Merge"的架构设计和执行方式以及它将对以太坊产生哪些长期影响。
那么，首先，什么是PoS呢？这就是我们将在博客文章的其余部分探讨的内容，包括合并是如何进行架构设计和执行的，以及它将对以太坊产生哪些长期影响。

2024-03-21 09:06 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +这就是我们谈论“最终性（finality）”时的意思。如果一个区块达到“finality”，它就无法恢复，除非出现严重的共识失败。
这就是我们谈论 **“最终确定”**（finality）时的意思。如果一个区块达到最终确定，它就无法恢复，除非出现严重的共识失败。

2024-03-21 12:50 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +回想一下，一个证明包含三票（源、目标、头）。每张投票都有资格获得奖励。验证者只会因“正确”的证明而获得奖励——这意味着他们的投票同意当前的区块提议者。此外，还有一个额外的权重，该权重取决于验证者在提出区块后进行证明的速度，值为基本奖励除以“inclusion delay”(衡量验证者提交的attestation在链上实际被记录所花费时间的指标。这个指标反映了验证者attestation的及时性。
回想一下，一个证明包含三票（源检查点、目标检查点、头区块）。每张投票都有资格获得奖励。验证者只会因“正确”的证明而获得奖励——这意味着他们的投票同意当前的区块提议者。此外，还有一个额外的权重，该权重取决于验证者在提出区块后进行证明的速度，值为基本奖励除以“纳入延迟”（inclusion delay）。（译者注：纳入延迟是衡量验证者提交的证明在链上实际被记录所花费时间的指标。这个指标反映了验证者证明的及时性。计算公式为验证者提交的证明在预期slot与实际记录在链上的slot之间的差值，然后对这些差值求平均。[来源](https://foresightnews.pro/article/detail/32979)）

2024-03-22 01:41 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +> "The proPoSer reward for a duty is the attester reward for that duty, multiplied by the proPoSer reward as a fraction of everything but the proPoSer reward."
thanks for your meticulous proofreading.

2024-03-22 07:36 UTC, dethan3 commented
close #4

2024-03-22 07:36 UTC, merged

2024-03-22 10:43 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +
事实上，难度炸弹一直是以太坊协议的一部分，因为以太坊希望能过渡到PoS。只不过这个时间比最初预期的要长得多。因此，协议进行了多次升级推迟难度炸弹，直到PoS准备好启动。

2024-03-22 10:56 UTC, sumisme945 commented on _posts/Article/Translation/How-does-the-NEW-Ethereum-work/how-does-the-new-ethereum-work.md
> +最后一个值的注意的变化块的固化，在PoW中，我们使用六次确认规则，如果在当前头块上构建了六个区块，那么就认为该块已经固化了。这只能说是大概率不变了，并不是100%，虽然可能性很小但是仍然有可能发生重组。
最后一个值的注意的变化是用户如何知道块已经最终确定，在PoW中，我们使用六次确认规则，如果在当前头块上构建了六个区块，那么就认为该块已经最终确定了。这只能说是大概率不变了，并不是100%可靠，虽然可能性很小但是仍然有可能发生重组。